-Failed tests
Test 1: Test 1
Test 2: Test 4
Test 3: Test 5
Test 4: Test 6
-Test 1: Test 1 (-25.000)
Incorrect program output
 --- Input ---
>35
>4
>36
>5
>35
>5
>32
>10
>34
>12
>33
>8
>37
>3
>0
>0
>

 --- Program output ---
>temperatura del dia:35
>¿Desea continuar S/N?temperatura del dia:36
>¿Desea continuar S/N?temperatura del dia:35
>¿Desea continuar S/N?temperatura del dia:32
>¿Desea continuar S/N?temperatura del dia:34
>¿Desea continuar S/N?temperatura del dia:33
>¿Desea continuar S/N?temperatura del dia:37
>¿Desea continuar S/N?temperatura del dia:0
>¿Desea continuar S/N?temperatura del dia:Traceback (most recent call last):
>  File "Reto3.py", line 13, in <module>
>    temperatura_dia=int(input("temperatura del dia:"))
>ValueError: invalid literal for int() with base 10: ''

 --- Expected output (numbers)---
>7
>3
>1
>1
>1
>33.5
>8.75
>42.85714286
>

-Test 2: Test 4 (-25.000)
Incorrect program output
 --- Input ---
>34
>12
>38
>4
>25
>22
>39
>12
>30
>3
>36
>9
>38
>11
>29
>2
>39
>14
>0
>0
>

 --- Program output ---
>temperatura del dia:34
>¿Desea continuar S/N?temperatura del dia:38
>¿Desea continuar S/N?temperatura del dia:25
>¿Desea continuar S/N?temperatura del dia:39
>¿Desea continuar S/N?temperatura del dia:30
>¿Desea continuar S/N?temperatura del dia:36
>¿Desea continuar S/N?temperatura del dia:38
>¿Desea continuar S/N?temperatura del dia:29
>¿Desea continuar S/N?temperatura del dia:39
>¿Desea continuar S/N?temperatura del dia:0
>¿Desea continuar S/N?temperatura del dia:Traceback (most recent call last):
>  File "Reto3.py", line 13, in <module>
>    temperatura_dia=int(input("temperatura del dia:"))
>ValueError: invalid literal for int() with base 10: ''

 --- Expected output (numbers)---
>9
>7
>2
>4
>1
>29.5
>17.0
>77.77777777777777

-Test 3: Test 5 (-25.000)
Incorrect program output
 --- Input ---
>36
>5
>35
>6
>34
>7
>0
>0
>

 --- Program output ---
>temperatura del dia:36
>¿Desea continuar S/N?temperatura del dia:35
>¿Desea continuar S/N?temperatura del dia:34
>¿Desea continuar S/N?temperatura del dia:0
>¿Desea continuar S/N?temperatura del dia:Traceback (most recent call last):
>  File "Reto3.py", line 13, in <module>
>    temperatura_dia=int(input("temperatura del dia:"))
>ValueError: invalid literal for int() with base 10: ''

 --- Expected output (numbers)---
>3
>1
>0
>1
>0
>34.5
>6.5
>33.333333333333336

-Test 4: Test 6 (-25.000)
Incorrect program output
 --- Input ---
>36
>5
>35
>6
>34
>7
>0
>0
>

 --- Program output ---
>temperatura del dia:36
>¿Desea continuar S/N?temperatura del dia:35
>¿Desea continuar S/N?temperatura del dia:34
>¿Desea continuar S/N?temperatura del dia:0
>¿Desea continuar S/N?temperatura del dia:Traceback (most recent call last):
>  File "Reto3.py", line 13, in <module>
>    temperatura_dia=int(input("temperatura del dia:"))
>ValueError: invalid literal for int() with base 10: ''

 --- Expected output (numbers)---
>3
>1
>0
>1
>0
>34.5
>6.5
>33.333333333333336

-Summary of tests
>+------------------------------+
>|  4 tests run/ 0 tests passed |
>+------------------------------+

